export const FakeData_menu_mb = [
  {
    name: "Rent",
    sub_item: [
      "House for rent in Bangkok",
      "Townhouse for rent in Bangkok",
      "Homeoffice for rent in Bangkok",
      "Condo for rent in Bangkok",
      "Apartment for rent in Bangkok",
      "Penthouse for rent in Bangkok",
      "Duplex condo for rent in Bangkok",
      "Office space for rent in Bangkok",
      "Retail for rent in Bangkok",
      "Shophouse for rent in Bangkok",
      "Warehouse for rent in Bangkok",
      "Building for rent in Bangkok",
      "Land for rent in Bangkok",
      "Property for rent in Bangkok",
    ],
  },
  {
    name: "Buy",
    sub_item: [
      "House for in Bangkok",
      "Townhouse for in Bangkok",
      "Homeoffice for in Bangkok",
      "Condo for rent in Bangkok",
      "Apartment for in Bangkok",
      "Penthouse for in Bangkok",
      "Duplex condo for in Bangkok",
      "Office space for in Bangkok",
      "Retail for in Bangkok",
      "Shophouse for in Bangkok",
      "Warehouse for in Bangkok",
      "Building for in Bangkok",
      "Land for in Bangkok",
      "Property for in Bangkok",
    ],
  },
  {
    name: "Projects",
    sub_item: [
      "Popular projects in Bangkok",
      "Popular projects in Chonburi",
      "Popular projects in Prachuap khiri Khan",
    ],
  },
];
