export const FakeData_menu_mb = [
  {
    name: "Rent",
    sub_item: [
      "House for rent in Bangkok",
      "Townhouse for rent in Bangkok",
      "Homeoffice for rent in Bangkok",
      "Condo for rent in Bangkok",
      "Apartment for rent in Bangkok",
      "Penthouse for rent in Bangkok",
      "Duplex condo for rent in Bangkok",
      "Office space for rent in Bangkok",
      "Retail for rent in Bangkok",
      "Shophouse for rent in Bangkok",
      "Warehouse for rent in Bangkok",
      "Building for rent in Bangkok",
      "Land for rent in Bangkok",
      "Property for rent in Bangkok",
    ],
  },
  {
    name: "Buy",
    sub_item: [
      "House sale for in Bangkok",
      "Townhouse sale for in Bangkok",
      "Homeoffice sale for in Bangkok",
      "Condo sale for rent in Bangkok",
      "Apartment sale for in Bangkok",
      "Penthouse sale for in Bangkok",
      "Duplex condo sale for in Bangkok",
      "Office space sale for in Bangkok",
      "Retail sale for in Bangkok",
      "Shophouse sale for in Bangkok",
      "Warehouse sale for in Bangkok",
      "Building for in Bangkok",
      "Land sale for in Bangkok",
      "Property sale for in Bangkok",
    ],
  },
  {
    name: "Projects",
    sub_item: [
      "Popular projects in Bangkok",
      "Popular projects in Chonburi",
      "Popular projects in Prachuap khiri Khan",
    ],
  },
];
